I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script
    you "I..."
Exception: Sayer 'you' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 19, in script
    you "I..."
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'you' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
AI Drawing Eng 1.0
Mon Oct 17 19:33:40 2022
